# docker-compose-search.yml starts "search" service and override some
# services to link them so they can use the "search" as well.
version: '3'

volumes:
  search_data:

services:

  web:
    links:
      - storage
      - database
      - cache
      - search

  celery:
    links:
      - storage
      - database
      - cache
      - search
    depends_on:
      - storage
      - azure-cli
      - search

  # You may need to increase the memory for vm
  # sudo sysctl -w vm.max_map_count=262144
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - search_data:/usr/share/elasticsearch/data

    # Remove elasticsearch log since it's useless and shows periodic
    # "flood stage disk watermark exceeded" all the time
    logging:
      driver: none
